---
# yaml-language-server: $schema=https://raw.githubusercontent.com/ishioni/CRDs-catalog/main/helm.toolkit.fluxcd.io/helmrelease_v2beta2.json
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: authentik2
spec:
  chart:
    spec:
      # renovate: registryUrl=https://charts.goauthentik.io
      chart: authentik
      version: 2024.2.2
      sourceRef:
        kind: HelmRepository
        name: authentik
        namespace: flux-system
  interval: 30m
  values:
    global:
      deploymentAnnotations:
        secret.reloader.stakater.com/reload: &secret authentik-secret
    server:
      replicas: 1
      initContainers:
        - name: init-db
          image: ghcr.io/onedr0p/postgres-init:16.2
          envFrom:
            - secretRef:
                name: *secret
      resources:
        requests:
          cpu: 50m
          memory: 500Mi
        limits:
          memory: 800Mi
      metrics:
        enabled: true
        serviceMonitor:
          enabled: true

      ingress:
        enabled: true
        ingressClassName: "nginx"
        annotations:
          cert-manager.io/cluster-issuer: letsencrypt-production
          kubernetes.io/tls-acme: "true"
          external-dns/is-public: "true"
          external-dns.alpha.kubernetes.io/target: ${SECRET_DOMAIN}
        hosts:
            hosts: 
              - &host "id-new.${SECRET_DOMAIN}"
            paths:
              - /

        tls:
          - secretName: tls.authentik2
            hosts:
              - *host

    worker:
      replicas: 1
      resources:
        requests:
          cpu: 50m
          memory: 500Mi
        limits:
          memory: 1200Mi

    authentik:
      email:
        use_ssl: true
        port: "465"
      log_level: debug
      error_reporting:
        enabled: false

    prometheus:
      rules:
        enabled: true
    redis:
      enabled: true
      auth:
        enabled: true
      master:
        persistence:
          enabled: true
          size: 1Gi
        resources:
          requests:
            cpu: 15m
            memory: 50Mi
          limits:
            memory: 100Mi
      commonConfiguration: |-
        # Enable AOF https://redis.io/topics/persistence#append-only-file
        appendonly yes
        # Disable RDB persistence, AOF persistence already enabled.
        save ""
        maxmemory 94371840
        maxmemory-policy allkeys-lru
      metrics:
        enabled: true
        serviceMonitor:
          enabled: true
        resources:
          requests:
            cpu: 10m
            memory: 10Mi
          limits:
            memory: 20Mi
  valuesFrom:
    - kind: Secret
      name: *secret
      valuesKey: AUTHENTIK_SECRET_KEY
      targetPath: authentik.secret_key
    - kind: Secret
      name: *secret
      valuesKey: SMTP_HOST
      targetPath: authentik.email.host
    - kind: Secret
      name: *secret
      valuesKey: SMTP_USERNAME
      targetPath: authentik.email.username
    - kind: Secret
      name: *secret
      valuesKey: SMTP_PASS
      targetPath: authentik.email.password
    - kind: Secret
      name: *secret
      valuesKey: SMTP_FROM
      targetPath: authentik.email.from
    - kind: Secret
      name: *secret
      valuesKey: POSTGRES_HOST
      targetPath: authentik.postgresql.host
    - kind: Secret
      name: *secret
      valuesKey: POSTGRES_USER
      targetPath: authentik.postgresql.user
    - kind: Secret
      name: *secret
      valuesKey: POSTGRES_PASS
      targetPath: authentik.postgresql.password
    - kind: Secret
      name: *secret
      valuesKey: POSTGRES_DB
      targetPath: authentik.postgresql.name
    - kind: Secret
      name: *secret
      valuesKey: REDIS_PASS
      targetPath: authentik.redis.password
    - kind: Secret
      name: *secret
      valuesKey: REDIS_PASS
      targetPath: redis.auth.password