apiVersion: v1
kind: Pod
metadata:
  annotations:
    reloader.stakater.com/last-reloaded-from: '{"type":"SECRET","name":"bazarr","namespace":"downloads","hash":"158ce15b863963025817240541ec4ddcc9d07858","containerRefs":["bazarr"],"observedAt":1710698129}'
  creationTimestamp: "2024-03-17T17:55:58Z"
  generateName: bazarr-548c9b98fb-
  labels:
    app.kubernetes.io/component: bazarr
    app.kubernetes.io/instance: bazarr
    app.kubernetes.io/name: bazarr
    pod-template-hash: 548c9b98fb
  name: bazarr-548c9b98fb-jbzpg
  namespace: downloads
  ownerReferences:
  - apiVersion: apps/v1
    blockOwnerDeletion: true
    controller: true
    kind: ReplicaSet
    name: bazarr-548c9b98fb
    uid: 16ba0ba1-a23a-4b62-8ec8-3b725689550f
  resourceVersion: "189151764"
  uid: 4e5a90bc-04ee-4dae-b737-fcfa245c5f3b
spec:
  automountServiceAccountToken: true
  containers:
  - env:
    - name: TZ
      value: America/New_York
    envFrom:
    - secretRef:
        name: bazarr
    image: ghcr.io/onedr0p/bazarr:1.4.2@sha256:113035f37f289f190781d9d728f2ebf56c895b972921820f5d30408427c837d9
    imagePullPolicy: IfNotPresent
    livenessProbe:
      failureThreshold: 3
      periodSeconds: 10
      successThreshold: 1
      tcpSocket:
        port: 6767
      timeoutSeconds: 1
    name: bazarr
    readinessProbe:
      failureThreshold: 3
      periodSeconds: 10
      successThreshold: 1
      tcpSocket:
        port: 6767
      timeoutSeconds: 1
    resources: {}
    startupProbe:
      failureThreshold: 30
      periodSeconds: 5
      successThreshold: 1
      tcpSocket:
        port: 6767
      timeoutSeconds: 1
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /config/backup
      name: backup
    - mountPath: /config
      name: config
    - mountPath: /media
      name: media
    - mountPath: /media2
      name: media2
    - mountPath: /media3
      name: media3
    - mountPath: /temp_dir
      name: temp
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-xzz7l
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: false
  initContainers:
  - envFrom:
    - secretRef:
        name: bazarr
    image: ghcr.io/onedr0p/postgres-init:16.2
    imagePullPolicy: IfNotPresent
    name: init-db
    resources: {}
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /config/backup
      name: backup
    - mountPath: /config
      name: config
    - mountPath: /media
      name: media
    - mountPath: /media2
      name: media2
    - mountPath: /media3
      name: media3
    - mountPath: /temp_dir
      name: temp
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-xzz7l
      readOnly: true
  nodeName: nuc13i7-3
  preemptionPolicy: PreemptLowerPriority
  priority: 0
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext:
    fsGroup: 568
    fsGroupChangePolicy: OnRootMismatch
    runAsGroup: 568
    runAsUser: 568
    supplementalGroups:
    - 65539
  serviceAccount: default
  serviceAccountName: default
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - name: backup
    nfs:
      path: /volume1/Kubernetes/bazarr
      server: 192.168.1.168
  - name: config
    persistentVolumeClaim:
      claimName: bazarr
  - name: media
    nfs:
      path: /volume1/Media
      server: 192.168.10.105
  - name: media2
    nfs:
      path: /volume1/Media2
      server: 192.168.1.168
  - name: media3
    nfs:
      path: /volume1/Media
      server: 192.168.10.150
  - name: temp
    nfs:
      path: /volume1/temp
      server: 192.168.1.168
  - name: kube-api-access-xzz7l
    projected:
      defaultMode: 420
      sources:
      - serviceAccountToken:
          expirationSeconds: 3607
          path: token
      - configMap:
          items:
          - key: ca.crt
            path: ca.crt
          name: kube-root-ca.crt
      - downwardAPI:
          items:
          - fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
            path: namespace
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2024-03-17T17:56:10Z"
    status: "True"
    type: PodReadyToStartContainers
  - lastProbeTime: null
    lastTransitionTime: "2024-03-17T17:56:10Z"
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2024-03-17T17:56:20Z"
    status: "True"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2024-03-17T17:56:20Z"
    status: "True"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2024-03-17T17:55:58Z"
    status: "True"
    type: PodScheduled
  containerStatuses:
  - containerID: containerd://3ad943d700350668b5c2945c34ea24c7870b23636498261d25fc6bbcfcb5144c
    image: sha256:f026fdca851cf001bd479c08bb4afaf3edc73dd99c6fc2ac2574619be222b703
    imageID: ghcr.io/onedr0p/bazarr@sha256:113035f37f289f190781d9d728f2ebf56c895b972921820f5d30408427c837d9
    lastState: {}
    name: bazarr
    ready: true
    restartCount: 0
    started: true
    state:
      running:
        startedAt: "2024-03-17T17:56:10Z"
  hostIP: 192.168.10.159
  hostIPs:
  - ip: 192.168.10.159
  initContainerStatuses:
  - containerID: containerd://2b60772b632fa423912c7a86d0af6656dff730b1d95cae9adbd7b769e3044a97
    image: ghcr.io/onedr0p/postgres-init:16
    imageID: ghcr.io/onedr0p/postgres-init@sha256:930a20e3ea8c82504d8e80f413d042d9936930d625fb098dd306b5aad427a151
    lastState: {}
    name: init-db
    ready: true
    restartCount: 0
    started: false
    state:
      terminated:
        containerID: containerd://2b60772b632fa423912c7a86d0af6656dff730b1d95cae9adbd7b769e3044a97
        exitCode: 0
        finishedAt: "2024-03-17T17:56:10Z"
        reason: Completed
        startedAt: "2024-03-17T17:56:09Z"
  phase: Running
  podIP: 10.42.7.33
  podIPs:
  - ip: 10.42.7.33
  qosClass: BestEffort
  startTime: "2024-03-17T17:55:58Z"
