apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app.kubernetes.io/component: main
    app.kubernetes.io/instance: sonarr
    app.kubernetes.io/name: sonarr
  name: config-sonarr-0
  namespace: downloads
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
  storageClassName: longhorn-config
