apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app.kubernetes.io/component: main
    app.kubernetes.io/instance: bazarr
    app.kubernetes.io/name: bazarr
  name: config-bazarr-0
  namespace: downloads
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  storageClassName: longhorn-config
