apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app.kubernetes.io/component: main
    app.kubernetes.io/instance: overseerr
    app.kubernetes.io/name: overseerr
  name: config-overseerr-0
  namespace: media
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: longhorn-config
