apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app.kubernetes.io/component: main
    app.kubernetes.io/instance: radarr
    app.kubernetes.io/name: radarr
  name: config-radarr-0
  namespace: downloads
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
  storageClassName: longhorn-config
