---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: overseerr
  namespace: media
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://bjw-s.github.io/helm-charts/
      chart: app-template
      version: 2.3.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s-charts
        namespace: flux-system
      interval: 5m

  install:
    createNamespace: true
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5

  values:

    controllers:
      main:
        type: statefulset
        annotations:
          reloader.stakater.com/auto: "true"

        statefulset:
          volumeClaimTemplates:
            - name: config
              accessMode: ReadWriteOnce
              size: 2Gi
              storageClass: longhorn-config
              globalMounts:
                - path: /app/config

        pod:
          enableServiceLinks: false
          securityContext:
            runAsUser: 568
            runAsGroup: 568
            fsGroup: 568
            fsGroupChangePolicy: "OnRootMismatch"

        containers:
          main:
            image:
              repository: ghcr.io/sct/overseerr
              tag: 1.33.2
            env:
              TZ: "America/New_York"
              LOG_LEVEL: "info"

    ingress:
      main:
        enabled: true
        className: "nginx"
        annotations:
          external-dns.alpha.kubernetes.io/target: "${SECRET_DOMAIN}"
          external-dns/is-public: "true"
          cert-manager.io/cluster-issuer: letsencrypt-production
        hosts:
          - host: "request.${SECRET_DOMAIN}"
            paths:
              - path: /
                service:
                  name: main
                  port: http
        tls:
          - hosts:
              - "request.${SECRET_DOMAIN}"
          - secretName: overseer-tls

    service:
      main:
        ports:
          http:
            port: 5055

    resources:
      requests:
        cpu: 15m
        memory: 291M
      limits:
        cpu: 500m
        memory: 3744M
