---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: overseerr
  namespace: media
spec:
  accessModes:
    - "ReadWriteOnce"
  resources:
    requests:
      storage: 10Gi
  storageClassName: longhorn-config
