---
# yaml-language-server: $schema=https://kubernetes-schemas.thesteamedcrab.com/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: jellystat-secrets
  namespace: media
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: jellystat
    creationPolicy: Owner
    template:
      data:
        # App
        JWT_SECRET: "{{ .jellystat_jwt }}"
        POSTGRES_IP: &dbHost "{{ .postgres_db_host }}"
        POSTGRES_PORT: "5432"
        POSTGRES_DB: &dbName jellystat
        POSTGRES_USER: &dbUser "{{ .jellystat_db_user }}"
        POSTGRES_PASSWORD: &dbPass "{{ .jellystat_db_pass }}"

        # Postgres Init
        INIT_POSTGRES_DBNAME: *dbName
        INIT_POSTGRES_HOST: *dbHost
        INIT_POSTGRES_USER: *dbUser
        INIT_POSTGRES_PASS: *dbPass
        INIT_POSTGRES_SUPER_PASS: "{{ .pgpassword }}"

  dataFrom:
    - extract:
        key: jellystat
    - extract:
        key: cloudnative-pg
