---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: tautulli
spec:
  interval: 30m
  chart:
    spec:
      # renovate: registryUrl=https://bjw-s.github.io/helm-charts/
      chart: app-template
      version: 3.0.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s-charts
        namespace: flux-system
      interval: 5m
  install:
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
  values:

    defaultPodOptions:
      securityContext:
        runAsUser: 568
        runAsGroup: 568
        fsGroup: 568
        fsGroupChangePolicy: "OnRootMismatch"

    controllers:
      tautulli:
        annotations:
          reloader.stakater.com/auto: "true"

        containers:
          app:
            image:
              repository: ghcr.io/onedr0p/tautulli
              tag: 2.13.4@sha256:6651957d4678206e0dc9d389f23d88067ffc40dbc601893140daa45ffca8b728

            env:
              TZ: "America/New_York"

            probes:
              liveness:
                enabled: true
              readiness:
                enabled: true
              startup:
                enabled: true
                spec:
                  failureThreshold: 30
                  periodSeconds: 5

    service:
      tautulli:
        controller: tautulli
        ports:
          http:
            port: 8181

    ingress:
      tautulli:
        enabled: true
        className: "nginx"
        hosts:
          - host: &host "tautulli.${INTERNAL_DOMAIN}"
            paths:
              - path: /
                service:
                  identifier: tautulli
                  port: http
        tls:
          - hosts:
              - *host
            secretName: tautulli-tls

    persistence:
      config:
        enabled: true
        existingClaim: tautulli
