---
# yaml-language-server: $schema=https://lds-schemas.pages.dev/dragonflydb.io/dragonfly_v1alpha1.json
apiVersion: dragonflydb.io/v1alpha1
kind: Dragonfly
metadata:
  name: dragonfly
spec:
  image: docker.dragonflydb.io/dragonflydb/dragonfly:v1.15.1
  replicas: 3
  snapshot:
    dir: "s3://dragonfly"
    cron: "0 * * * *"
  envFrom:
    - secretKey:
        name: dragonfly-bkup
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 500m
      memory: 1280Mi
  args:
    - "--maxmemory=1128Mi"
    - "--proactor_threads=4"
    - "--cluster_mode=emulated"
    - "--dir s3://dragonfly" 
    - "--s3_endpoint s3://minio.${SECRET_DOMAIN}"
  snapshot:
    cron: "* * * * *"
    persistentVolumeClaimSpec:
      storageClassName: local-hostpath
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 1Gi