---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jellyfin-config
spec:
  accessModes:
    - "ReadWriteOnce"
  resources:
    requests:
      storage: 200Gi
  storageClassName: longhorn-config
