---
# yaml-language-server: $schema=https://raw.githubusercontent.com/ishioni/CRDs-catalog/main/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: &name bazarr-secrets
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: bazarr
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        POSTGRES_HOST: &dbHost "{{ .postgres_db_host }}"
        POSTGRES_PORT: "5432"
        POSTGRES_USER: &dbUser "{{ .bazarr_postgres_user }}"
        POSTGRES_PASSWORD: &dbPass "{{ .bazarr_postgres_pass }}"
        POSTGRES_DB: &dbName bazarr
        INIT_POSTGRES_DBNAME: *dbName
        INIT_POSTGRES_HOST: *dbHost
        INIT_POSTGRES_USER: *dbUser
        INIT_POSTGRES_PASS: *dbPass
        INIT_POSTGRES_SUPER_PASS: "{{ .pgpassword }}"
  dataFrom:
    - extract:
        key: cloudnative-pg
    - extract:
        key: bazarr
