---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: prowlarr
  namespace: downloads
spec:
  interval: 30m
  chart:
    spec:
      # renovate: registryUrl=https://bjw-s.github.io/helm-charts/
      chart: app-template
      version: 3.0.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s-charts
        namespace: flux-system

  install:
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5

  values:

    defaultPodOptions:
      securityContext:
        runAsUser: 568
        runAsGroup: 568
        fsGroup: 568
        fsGroupChangePolicy: OnRootMismatch
        supplementalGroups:
          - 65539

    controllers:
      prowlarr:
        annotations:
          reloader.stakater.com/auto: "true"

        containers:
          prowlarr:
            image:
              repository: ghcr.io/onedr0p/prowlarr-nightly
              tag: 1.14.3.4324
            env:
              TZ: "America/New_York"
              PROWLARR__AUTHENTICATION_METHOD: External
              PROWLARR__PORT: &port 9696

            probes:
              liveness:
                enabled: true
              readiness:
                enabled: true
              startup:
                enabled: true
                spec:
                  failureThreshold: 30
                  periodSeconds: 5

    service:
      prowlarr:
        controller: prowlarr
        ports:
          http:
            port: 9696

    ingress:
      prowlarr:
        enabled: true
        className: "nginx"
        hosts:
          - host: &host "prowlarr.${INTERNAL_DOMAIN}"
            paths:
              - path: /
                service:
                  identifier: prowlarr
                  port: http
        tls:
          - hosts:
              - *host
            secretName: prowlarr.tls

    persistence:
      config:
        existingClaim: prowlarr

      backup:
        type: nfs
        server: "${NAS2_ADDR}"
        path: /volume1/Kubernetes/prowlarr
        globalMounts:
          - path: /config/Backups
