---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prowlarr
  namespace: downloads
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: longhorn-config
