---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: sabnzbd
  namespace: downloads
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://bjw-s.github.io/helm-charts/
      chart: app-template
      version: 2.4.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s-charts
        namespace: flux-system
      interval: 30m

  install:
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5

  values:
    controllers:
      main:
        type: statefulset

        statefulset:
          volumeClaimTemplates:
            - name: config
              accessMode: ReadWriteOnce
              size: 2Gi
              storageClass: longhorn-config
              globalMounts:
                - path: /config

        annotations:
          reloader.stakater.com/auto: "true"

        pod:
          securityContext:
            runAsUser: 568
            runAsGroup: 568
            fsGroup: 568
            fsGroupChangePolicy: OnRootMismatch
            supplementalGroups:
              - 65539

        containers:
          main:
            image:
              repository: ghcr.io/onedr0p/sabnzbd
              tag: 4.1.0@sha256:1c1650511f96108e81d677abe8a2e491507caa023fdc5c2bfc99df087634c9f3
            env:
              TZ: "America/New_York"
              SABNZBD__PORT: &port 8080

    service:
      main:
        ports:
          http:
            port: *port

    ingress:
      main:
        enabled: true
        className: "nginx"
        hosts:
          - host: &host "sabnzbd.${INTERNAL_DOMAIN}"
            paths:
              - path: /
                service:
                  name: main
                  port: http
        tls:
          - hosts:
              - *host
          - secretName: sabnzbd-tls


    persistence:

      downloads:
        enabled: true
        existingClaim: sabnzbd-downloads-v1
        globalMounts:
          - path: /downloads

      temp:
        type: nfs
        server: "${NAS1_ADDR}"
        path: /volume1/temp
        globalMounts:
          - path: /temp_dir

    resources:
      requests:
        memory: 250Mi
        cpu: 500m
      limits:
        memory: 16384Mi
