---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: sabnzbd
  namespace: downloads
spec:
  interval: 30m
  chart:
    spec:
      # renovate: registryUrl=https://bjw-s.github.io/helm-charts/
      chart: app-template
      version: 3.0.2
      sourceRef:
        kind: HelmRepository
        name: bjw-s-charts
        namespace: flux-system
      interval: 30m

  install:
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5

  values:

    defaultPodOptions:
      securityContext:
        runAsUser: 568
        runAsGroup: 568
        fsGroup: 568
        fsGroupChangePolicy: OnRootMismatch
        supplementalGroups:
          - 65539

    controllers:
      sabnzbd:

        annotations:
          reloader.stakater.com/auto: "true"

        containers:
          sabnzbd:
            image:
              repository: ghcr.io/onedr0p/sabnzbd
              tag: 4.2.3@sha256:2daf5e89096f47f4d3a0c28f0bf84323f91b797c30d4efe3d7f29f2121bc0f3c
            env:
              TZ: "America/New_York"
              SABNZBD__PORT: &port 8080

    service:
      sabnzbd:
        controller: sabnzbd
        ports:
          http:
            port: *port

    ingress:
      sabnzbd:
        enabled: true
        className: "nginx"
        hosts:
          - host: &host "sabnzbd.${INTERNAL_DOMAIN}"
            paths:
              - path: /
                service:
                  identifier: sabnzbd
                  port: http
        tls:
          - hosts:
              - *host
            secretName: sabnzbd.tls


    persistence:

      config:
        enabled: true
        existingClaim: sabnzbd

      downloads:
        enabled: true
        existingClaim: sabnzbd-downloads-v1
        globalMounts:
          - path: /downloads

      temp:
        type: nfs
        server: "${NAS1_ADDR}"
        path: /volume1/temp
        globalMounts:
          - path: /temp_dir

    resources:
      requests:
        memory: 250Mi
        cpu: 500m
      limits:
        memory: 16384Mi
