---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sabnzbd
  namespace: downloads
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
  storageClassName: longhorn-config
