---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: sonarr
  namespace: downloads
spec:
  interval: 30m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: app-template
      version: 2.6.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s-charts
        namespace: flux-system
  install:
    remediation:
      retries: 5
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 5

  values:
    controllers:
      main:

        annotations:
          reloader.stakater.com/auto: "true"
        pod:
          securityContext:
            runAsUser: 568
            runAsGroup: 568
            fsGroup: 568
            fsGroupChangePolicy: OnRootMismatch
            supplementalGroups:
              - 65539

        containers:
          main:
            image:
              repository: ghcr.io/onedr0p/sonarr-develop
              tag: 4.0.2.1312@sha256:f98240a60350e381259f0021c4083053c80d42a72f4543fc61911f4084f55fb9
            env:
              TZ: "America/New_York"
              SONARR__INSTANCE_NAME: Sonarr
              SONARR__PORT: &port 8989
              SONARR__LOG_LEVEL: info

    service:
      main:
        ports:
          http:
            port: *port

    ingress:
      main:
        enabled: true
        className: nginx
        hosts:
          - host: &host "sonarr.${INTERNAL_DOMAIN}"
            paths:
              - path: /
                service:
                  name: main
                  port: http
        tls:
          - hosts:
              - *host
          - secretName: sonarr-tls

    persistence:

      config:
        enabled: true
        existingClaim: sonarr

      media:
        type: nfs
        server: "${NAS1_ADDR}"
        path: /volume1/Media
        globalMounts:
          - path: /media

      media2:
        type: nfs
        server: "${NAS2_ADDR}"
        path: /volume1/Media2
        globalMounts:
          - path: /media2

      media3:
        type: nfs
        server: "${NAS3_ADDR}"
        path: /volume1/Media
        globalMounts:
          - path: /media3

      temp:
        type: nfs
        server: "${NAS1_ADDR}"
        path: /volume1/temp
        globalMounts:
          - path: /temp_dir

      backups:
        type: nfs
        server: "${NAS2_ADDR}"
        path: /volume1/Kubernetes/sonarr
        globalMounts:
          - path: /config/Backups
