---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: radarr
  namespace: downloads
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://bjw-s.github.io/helm-charts/
      chart: app-template
      version: 2.0.3
      sourceRef:
        kind: HelmRepository
        name: bjw-s-charts
        namespace: flux-system
      interval: 30m

  install:
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
  values:

    controllers:
      main:
        type: statefulset

        annotations:
          reloader.stakater.com/auto: "true"

        statefulset:
          volumeClaimTemplates:
            - name: config
              accessMode: ReadWriteOnce
              size: 100Gi
              storageClass: longhorn-config
              globalMounts:
                - path: /config
        pod:
          securityContext:
            runAsUser: 568
            runAsGroup: 568
            fsGroup: 568
            fsGroupChangePolicy: OnRootMismatch
            supplementalGroups:
              - 65539

        containers:
          main:
            image:
              repository: ghcr.io/onedr0p/radarr-develop
              tag: 5.0.3.8127@sha256:efe518bdc1d29bda31d4aa7177b2881a7f47f114c067e662415d72abc0a0e9ea

            env:
              TZ: "America/New_York"
              RADARR__PORT: &port 7878
              RADARR__AUTHENTICATION_METHOD: External

    service:
      main:
        ports:
          http:
            port: *port

    ingress:
      main:
        enabled: true
        className: "nginx"
        hosts:
          - host: &host "radarr.${INTERNAL_DOMAIN}"
            paths:
              - path: /
                service:
                  name: main
                  port: http
        tls:
          - hosts:
              - *host
          - secretName: radarr-tls

    persistence:
      media:
        type: nfs
        server: "${NAS1_ADDR}"
        path: /volume1/Media
        globalMounts:
          - path: /media

      backups:
        type: nfs
        server: "${NAS2_ADDR}"
        path: /volume1/Kubernetes/radarr
        globalMounts:
          - path: /config/Backups

      temp:
        type: nfs
        server: "${NAS1_ADDR}"
        path: /volume1/temp
        globalMounts:
          - path: /temp_dir
