---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: radarr
  namespace: downloads
spec:
  accessModes:
    - "ReadWriteOnce"
  resources:
    requests:
      storage: 100Gi
  storageClassName: longhorn-config
