---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps-plex2
  namespace: flux-system
  labels:
    substitution.flux.home.arpa/enabled: "true"
spec:
  dependsOn:
    - name: cluster-apps-intel-device-plugins-gpu
    - name: cluster-apps-longhorn-recurring-jobs
  path: ./kubernetes/apps/media/plex2/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2beta1
      kind: HelmRelease
      name: plex2
      namespace: media
  interval: 30m
  retryInterval: 1m
  timeout: 3m
  wait: false
