apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:ENAosPnCi8LysMGT5NRUIBDr,iv:eqzv3+WXsVEekAidjBYbld+8aY0GLtIGHktcNhL0q5U=,tag:Dnqw2CG+Y4zZ8qX+jKB6SQ==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:W3LX+sPBPKolb9st0tYULGWZvO+X4Yz3U7wYVo7Q07QTPgv0,iv:l/M5cjzbL1GrdJbE8xqAH+KhlpggbIjfjNzo3l2IC+4=,tag:ziwjRgve41VothVVfLVN5Q==,type:str]
    SECRET_DOMAIN: ENC[AES256_GCM,data:v/7WG1P8zCwShGwOPkg=,iv:jkoGAOEgPnXLvXPUd7CNrTBrCWbKZwY1e4zSxHIfeQY=,tag:x4yDoJX5EagYHtsKVyEeBg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1pqmv9umk70z2xyv8vvlma070d9rzr02j3ye8gjyv64ddf0sfwccspwsj8d
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5MnZ2c1NZb2l5LzNBVVRK
            ZDFOTkhML2V3RG16bjQ0ZThDYnI0ZDFjZlcwCjRDZmVjVzMyWHlJYlRNejROM0ls
            bC9pRE9wM3NsWis3a2NsT1g5RFdYbkUKLS0tIFJvc2lpdGdLbG56STFYYnJsQUto
            SHJ4ZnJpTEdyK3g3MjFqUnVVSnJyUUkKao3pDcT5SLF6hYpPDjg6J8Z9VqUvhh/k
            0Bh5YNCgEfpolXXMWRwqImQ7LMm5ewqrBmrWmyKgsTq4ucPgjP9qCg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-09-20T08:51:50Z"
    mac: ENC[AES256_GCM,data:hwGqIOd6veoHZaIFmZlJHjvMf0OhYLktiFO3ANgSNHpem+dubtzs5+vYCHWtKdpwqLtd32XKitewkvWvRg2JdEoZdZ5fBKN626SbhpQ5ftOciR/rcki6pWRe2CqeDYH6dKwuZAZrp+SgXD5+9kyJXP4Z6oqOf9fqeRrU37SxzMM=,iv:AuzGyLT+WVRZ/L79ntV9C0S/kSe1+urfRc3r6TGdKuo=,tag:CZM8eP17iBWmV8wPY9NYhw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.0
