---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: plex
  namespace: media
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://bjw-s.github.io/helm-charts/
      chart: app-template
      version: 2.6.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s-charts
        namespace: flux-system
      interval: 5m

  install:
    createNamespace: true
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5

  dependsOn:
    - name: intel-device-plugin-gpu
      namespace: kube-system
    - name: longhorn
      namespace: storage

  values:
    controllers:
      main:
        type: statefulset
        annotations:
          reloader.stakater.com/auto: "true"

        statefulset:
          volumeClaimTemplates:
            - name: config
              accessMode: ReadWriteOnce
              size: 20Gi
              storageClass: longhorn-plex
              globalMounts:
                - path: /config

        pod:
          enableServiceLinks: false
          nodeSelector:
            intel.feature.node.kubernetes.io/gpu: "true"
          securityContext:
            runAsUser: 568
            runAsGroup: 568
            fsGroup: 568
            fsGroupChangePolicy: "OnRootMismatch"
            supplementalGroups:
              - 44
              - 105
              - 100
              - 106
              - 65539

        containers:
          main:
            image:
              repository: ghcr.io/onedr0p/plex-beta
              tag: 1.40.1.8173-3e92df2db@sha256:2d03a4cc820faff2f7299ea880441571e47b9205913eb1058a986e7ec3bac3d3
            env:
              TZ: "America/New_York"
              ADVERTISE_IP: "http://${PLEX_LB}:32410/"
              HOSTNAME: "plex-cluster"
              PLEX_CLAIM: ${PLEX_CLAIM}
            resources:
              requests:
                gpu.intel.com/i915: 1
                cpu: 1000m
                memory: 16G
              limits:
                gpu.intel.com/i915: 1
                memory: 64G

    service:
      main:
        enabled: true
        type: LoadBalancer
        annotations:
          io.cilium/lb-ipam-ips: ${PLEX_LB}
          metallb.universe.tf/allow-shared-ip: plex
        externalTrafficPolicy: Cluster
        ports:
          http:
            port: 32410
            targetPort: 32400
            protocol: TCP

    ingress:
      main:
        enabled: true
        className: "nginx"
        annotations:
          external-dns.alpha.kubernetes.io/target: "${SECRET_DOMAIN}"
          external-dns/is-public: "true"
          cert-manager.io/cluster-issuer: letsencrypt-production
          nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
        hosts:
          - host: &host "plex.${SECRET_DOMAIN}"
            paths:
              - path: /
                service:
                  name: main
                  port: http
        tls:
          - hosts:
              - *host
          - secretName: plex-tls-secret

    persistence:
      media:
        type: nfs
        server: "${NAS1_ADDR}"
        path: /volume1/Media
        globalMounts:
          - path: /media
            readOnly: true

      media2:
        type: nfs
        server: "${NAS2_ADDR}"
        path: /volume1/Media2
        globalMounts:
          - path: /media2
            readOnly: true

      media3:
        type: nfs
        server: "${NAS3_ADDR}"
        path: /volume1/Media
        globalMounts:
          - path: /media3
            readOnly: true

      backups:
        type: nfs
        server: "${NAS2_ADDR}"
        path: /volume1/Kubernetes/plex
        globalMounts:
          - path: /backups

      transcode:
        type: emptyDir
        globalMounts:
          - path: /transcode

      plex-cache:
        existingClaim: plex-cache
        globalMounts:
          - path: /config/Library/Application Support/Plex Media Server/Cache
