---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: plex-bkp
  namespace: media
spec:
  accessModes:
    - "ReadWriteOnce"
  resources:
    requests:
      storage: 300Gi
  storageClassName: longhorn
