---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: &name minio-secret
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: *name
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        NAS3_ADDR: "{{ .nas3_addr }}"
        MINIO_NFS_PATH: "{{ .minio_nfs_path }}"
  dataFrom:
    - extract:
        key: nas-info
    - extract:
        key: minio