---
# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/v1.26.1-standalone-strict/storageclass-storage-v1.json
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: &provisioner nfs-provisioner
  labels:
    app.kubernetes.io/name: *provisioner
    kustomize.toolkit.fluxcd.io/substitute: disabled
provisioner: *provisioner
allowVolumeExpansion: true
reclaimPolicy: Delete
parameters:
  pathPattern: ${.PVC.namespace}-${.PVC.name}
  onDelete: retain
mountOptions:
  - nfsvers=4
  - nolock
  - soft
  - rw
