---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: &app lidarr
  namespace: downloads
spec:
  interval: 10m
  chart:
    spec:
      chart: app-template
      version: 2.0.2
      sourceRef:
        kind: HelmRepository
        name: bjw-s-charts
        namespace: flux-system
  maxHistory: 3
  install:
    remediation:
      retries: 3

  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3

  dependsOn:
    - name: longhorn
      namespace: storage

  uninstall:
    keepHistory: false

  values:

    controllers:
      main:
        type: statefulset

        annotations:
          reloader.stakater.com/auto: "true"

        statefulset:
          volumeClaimTemplates:
            - name: config
              accessMode: ReadWriteOnce
              size: 10Gi
              storageClass: longhorn-config
              globalMounts:
                - path: /config
        pod:
          securityContext:
            runAsUser: 568
            runAsGroup: 568
            fsGroup: 568
            fsGroupChangePolicy: OnRootMismatch
            supplementalGroups:
              - 65539

        containers:
          main:
            image:
              repository: ghcr.io/onedr0p/lidarr-develop
              tag: 1.4.3.3586@sha256:d7a6819c6f60719d4de5487e32ff555c916cdb31fe4c82574d7b6f2a84b40897

    service:
      main:
        ports:
          http:
            port: 8686

    ingress:
      main:
        enabled: true
        className: "nginx"
        hosts:
          - host: &host lidarr.${INTERNAL_DOMAIN}
            paths:
              - path: /
                service:
                  name: main
                  port: http
        tls:
          - hosts:
              - *host
            secretName: lidarr-tls

    persistence:

      media:
        type: nfs
        server: "${NAS1_ADDR}"
        path: /volume1/Media/Music
        globalMounts:
          - path: /media

      temp:
        type: nfs
        server: "${NAS1_ADDR}"
        path: /volume1/temp
        globalMounts:
          - path: /temp_dir
