---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: lidarr
  namespace: downloads
spec:
  accessModes:
    - "ReadWriteOnce"
  resources:
    requests:
      storage: 10Gi
  storageClassName: longhorn-config
